### ISSUE TITLE
Update Readme With Getting Started Guide and How to Contribute

### ISSUE THREAD

**Issue by dcjc29** [ms-club-sliit/msclubwebsite#19]

**Comment by gihanrcg** [comment]
This is urgernt :hurtrealbad:

**Comment by gihanrcg** [comment]
Any update on this ? @dcjc29 ? @swsjonathan ? @Nishiki97 ?

**Comment by gihanrcg** [comment]
Asking again after 17 days. Any progress at all ? @dcjc29 @swsjonathan @Nishiki97

**Comment by swsjonathan** [comment]
I have already started working on this. Will have the Readme ready by 13th. 
Parallely working on the "About Us" content.

**Comment by gihanrcg** [comment]
Only you ? What about other two assignees ?
