### ISSUE TITLE
Introduce JEST unit testing

### ISSUE THREAD

**Issue by gihanrcg** [ms-club-sliit/msclubwebsite#25]
For this project, there is absolutely no use of unit tests. However, if we practise using unit tests in this project, it will help us a lot in the next big projects. 

We can start with small unit tests to test simple things.
And make it a prerequisite to the pre commit hook

**Comment by lwpamihiranga** [comment]
Docs on Unit Testing - https://create-react-app.dev/docs/running-tests/

**Comment by gihanrcg** [comment]
@lwpamihiranga can you take this up ?

**Comment by lwpamihiranga** [comment]
@gihanrcg sure aiye. i assigned it to myself
