### ISSUE TITLE
Need file extension correction - WhatWeDoSection.js

### ISSUE THREAD

**Issue by lwpamihiranga** [ms-club-sliit/msclubwebsite#31]
@rusiruavb  `src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js` this file should also be changed to `.jsx` I guess

correct me if wrong
cc: @gihanrcg @Shehanka

**Comment by gihanrcg** [comment]
Yes. It should be changed

**Comment by rusiruavb** [comment]
> @rusiruavb  `src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js` this file should also be changed to `.jsx` I guess
> 
> correct me if wrong
> cc: @gihanrcg @Shehanka 

Actually, when I convert that file into .jsx the application throws an exception. I will look other available solutions and if I found one, I will change it to .jsx format.

**Comment by gihanrcg** [comment]
after you change the extension, you should restart the server. Otherwie the server cannot identify the file

**Comment by rusiruavb** [comment]
I have also done that. But still throws the exception. That's why I keep that file in a .js format

**Comment by gihanrcg** [comment]
Looking into it at the momentnt

**Comment by lwpamihiranga** [comment]
https://github.com/ms-club-sliit/msclubwebsite/blob/16fa1faad18a98e9c625099bdd53113e1e169422/src/modules/AboutUsModules/WhatWeDoSection/WhatWeDoSection.js#L6-L20

I think the issue should be within these lines

**Comment by rusiruavb** [comment]
This is the exception that throws from the application.
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
