### ISSUE TITLE
Static Website Design

### ISSUE THREAD

**Issue by dcjc29** [ms-club-sliit/msclubwebsite#4]

**Comment by gihanrcg** [comment]
This is completed right ??
@Bawanthathilan @dcjc29

**Comment by Bawanthathilan** [comment]
> This is completed right ??
> @Bawanthathilan @dcjc29

yes

**Comment by gihanrcg** [comment]
> > This is completed right ??
> > @Bawanthathilan @dcjc29
> 
> yes

Closing the issue
