### ISSUE TITLE
Remove focus border in view more button

### ISSUE THREAD

**Issue by gihanrcg** [ms-club-sliit/msclubwebsite#81]
![image](https://user-images.githubusercontent.com/37530996/125785997-5b2abbcf-e3cf-41fd-8d6d-872979de1b90.png)

When we click view more arrows, an ugly border is left behind. That need to be removed. 
It is better if we can add add slight color change on hover

**Comment by rusiruavb** [comment]
@gihanrcg what if we just remove entire **view more** item from that component. Because we already have swipe option for cards. I think this is an additional click to our site. This is just my opinion. What you think aiya?

**Comment by swsjonathan** [comment]
If we remove it, we'll have to add a visual cue to indicate that it scrollable. 
One way of doing it to have half of the next component visible. 
![image](https://user-images.githubusercontent.com/41731232/125795996-656aaf2a-e5ec-4366-808e-bb1dea4089a9.png)

Or else we could us a better indicator arrow to show it is scrollable

**Comment by gihanrcg** [comment]
Anyway we need to indicate that there are more to see and it is scrollable. Let's keep it as it is, but lets change the styling little bit

**Comment by rusiruavb** [comment]
Yes, we have to implement that just like LinkedIn one.  I'm currently implementing it

**Comment by rusiruavb** [comment]
I will share some images after I change that view. If all are ok with the change then only we can implement that change into the site.

**Comment by rusiruavb** [comment]
finished
