### ISSUE TITLE
The social link media buttons do not not matching the general theme

### ISSUE THREAD

**Issue by gihanrcg** [ms-club-sliit/msclubwebsite#82]
![image](https://user-images.githubusercontent.com/37530996/125786483-2c1e2d1d-d0be-4ef2-bcda-e475db5f728d.png)

Thoughts ?
@Bawanthathilan @swsjonathan @Shehanka

**Comment by swsjonathan** [comment]
Yeah seems odd. 
1. Either we can make it all green color, but this would make, 3 of the logos have different colors than its usual (FB, Twitter, LinkedIn)
2. Or we could have the logos white and have a green gradient background for the speaker card like this. 
[image](https://user-images.githubusercontent.com/41731232/125790811-6a9b8de7-4f02-4812-91c0-74f53d294796.png)

**Comment by rusiruavb** [comment]
We can make icons color similar to our theme color

**Comment by rusiruavb** [comment]
I will change the speaker icon color to theme color in the next PR

**Comment by gihanrcg** [comment]
@rusiruavb can we see that in the figma first ? So that we have an idea how that looks

**Comment by gihanrcg** [comment]
Because I am afraid we will have too much green :joy:

**Comment by rusiruavb** [comment]
Aa.. ok aiya 👍🏻

**Comment by rusiruavb** [comment]
@gihanrcg aiya now I have change social medial icon colours to our theme colour.
